<!DOCTYPE html>
<html>
	<head>
		<title>SuperChat</title>
		<link rel="stylesheet" type="text/css" href="css/style.css">
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
		
		<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
		<script src="js/events.js"></script>
		<script src="js/chat.js"></script>
	</head>
	<body>
		<form>
			<ul id="zone_chat"></ul>
			<ul id="zone_user"></ul>

			<input type="text" placeholder="Votre message ici" id="message" />
			<input type="button" value="Envoyer" id="send" />
		</form>

		<script src="js/main.js"></script>
	</body>	
</html>